services:
  postgres:
    image: postgres:16
    container_name: agenda-postgres
    environment:
      POSTGRES_DB: AgendaVirtual
      POSTGRES_USER: ADMINISTRADOR
      POSTGRES_PASSWORD: 123456
    ports:
      - "5432:5432"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: agendavirtual-app
    ports:
      - "4444:4444"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/AgendaVirtual
      SPRING_DATASOURCE_USERNAME: ADMINISTRADOR
      SPRING_DATASOURCE_PASSWORD: 123456